@base="http://localhost:8080/api/v1"

# Create Group

POST {{base}}/groups
Content-Type: application/json
{
  "name": "group"
}

# List Groups

GET {{base}}/groups?limit=5&offset=0

# Update Groups

PUT {{base}}/groups/608970d1-5061-43a7-a4fe-5c3d4d8b93ac/
Content-Type: application/json
{
  "name": "test 1"
}


# Delete Group

DELETE {{base}}/groups/532870e6-6b01-40f9-ad9c-ff1ef59623ec/

## Categories

POST {{base}}/categories/
Content-Type: application/json
{
  "name": "Category 25",
  "group_id": "44e90df5-f1e9-49f6-9878-a649bcd91c35"
}

# List Categories

GET {{base}}/categories/?limit=10&offset=0

# Update Category

PUT {{base}}/categories/78fc0ddb-e650-45fa-8cda-6e8a2274e4fd/
{
  "name": "New name 12",
  "group_id": "44e90df5-f1e9-49f6-9878-a649bcd91c35"
}


# Delete Category

DELETE {{base}}/categories/b2d2a16e-9443-48d2-bd05-a39398db659d/
